twig:
    globals:
        site_name: '%app.name%'
    file_name_pattern: '*.twig'
    # form_themes: ['tailwind_2_layout.html.twig']
    form_themes: ['form/form_theme.html.twig']

when@test:
    twig:
        strict_variables: true
