controllers:
    resource: routing.controllers

app_home_redirect:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: app_user_board
        permanent: false
